url: "https://oliverh32.github.io/15618-final-project/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "15618 Final Project: Parallel Gradient Boosting Decision Tree" # the name of your site, e.g. ACME Corp.
description: "jiayuan3 & qinxinw"
